eureka:
  instance:
     preferIpAddress: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
       defaultZone: http://microservices-refapp-eureka-chrisking.mybluemix.net/eureka/

# Server configuration
server:
  context-path: /micro
  port: 8080

# Spring properties
spring:
  application:
     name: customer-microservice
     
     cloudant:
        username: 
        password: 
        host: 
        port: 443
        database: customers

     keyprotect:
        api-endpoint: ibm-key-protect.edge.bluemix.net
        bluemix-space-guid: 
        bluemix-org-guid: 
        oauth-token: 
        refresh-token: 